---
title: "Evo_Geno_Lab7"
author: "Danaiijah Vilsaint"
date: "10/12/2020"
output: html_document
---

## my computer would freeze evrytime I tried to do it so its not completed
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(BiocStyle)
```

```{r}
library(knitr)
opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE,
               cache = FALSE, fig.width = 5, fig.height = 5)
```


```{r}
library(rmarkdown)
```
```{r}
dir <- system.file("extdata", package="airway", mustWork=TRUE)
```


```{r}
csvfile <- file.path(dir, "sample_table.csv")
coldata <- read.csv(csvfile, row.names=1, stringsAsFactors=FALSE)
coldata
```


```{r}
coldata <- coldata[1:2,]
coldata$names <- coldata$Run
coldata$files <- file.path(dir, "quants", coldata$names, "quant.sf.gz")
file.exists(coldata$files)

```

```{r}
par(mar=c(0,0,0,0))
plot(1,1,xlim=c(0,100),ylim=c(0,100),bty="n",
     type="n",xlab="",ylab="",xaxt="n",yaxt="n")
polygon(c(45,90,90,45),c(5,5,70,70),col="pink",border=NA)
polygon(c(45,90,90,45),c(68,68,70,70),col="pink3",border=NA)
text(67.5,40,"assay(s)")
text(67.5,35,'e.g. "counts", ...')
polygon(c(10,40,40,10),c(5,5,70,70),col="skyblue",border=NA)
polygon(c(10,40,40,10),c(68,68,70,70),col="skyblue3",border=NA)
text(25,40,"rowRanges")
polygon(c(45,90,90,45),c(75,75,95,95),col="palegreen",border=NA)
polygon(c(45,47,47,45),c(75,75,95,95),col="palegreen3",border=NA)
text(67.5,85,"colData")
```

```{r}
library("tximeta")
se <- tximeta(coldata)
```

```{r}
dim(se)
head(rownames(se))
```
```{r}
gse <- summarizeToGene(se)
```
```{r, eval=FALSE}
dim(gse)
head(rownames(gse))no
```

```{r}
data(gse)
gse
```










