---
title: "Evo_Geno_Lab4_Covid"
author: "Danaiijah Vilsaint"
Date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```
```{r}
report_03_11_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
```
```{r, eval=FALSE}
str(report_03_11_2020)
```

```{r, eval=FALSE}
View(report_03_11_2020)
```
```{r}
library(DT)
datatable(report_03_11_2020)
```

### Exercise 1
```{r}
report_09_13_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-13-2020.csv"))
```

```{r}
report_03_11_2020 <-   read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-11-2020.csv")) %>%
  rename(Country_Region = "Country/Region", Province_State = "Province/State")
```

```{r}
str(report_09_13_2020)
```
```{r, eval=FALSE}
View(report_09_13_2020)
```
```{r, eval=FALSE}
View(report_03_11_2020)
```

### Exercise 2
```{r, eval=FALSE}
country<-report_03_11_2020%>%group_by(Country_Region) %>% summarise(Deaths= sum(Deaths))

```
### Exercise 3
```{r, eval=FALSE}
(US<-report_03_11_2020)%>%
filter(Country_Region=="US") %>% 
group_by(Province_State) %>% 
summarise(Deaths= sum(Deaths)) %>% 
slice(1:10)
```

### Exercise 4
```{r, eval=FALSE}
Deaths<-country%>%
arrange(desc(Deaths))%>%
slice(1:10)
View(Deaths)
```



```{r, eval=FALSE}
country2<-report_03_11_2020%>%group_by(Country_Region) %>% summarise(Confirmed= sum(Confirmed))
```
```{r, eval=FALSE}
Confirmed<-country2%>%
arrange(desc(Confirmed))%>%
slice(1:10)
View(Confirmed)
```
### Exercise 5 March
```{r, eval=FALSE}
ggplot(data = Death, aes(x = Country_Region , y= Deaths, color = Country_Region)) + geom_point() + theme(legend.position="none") #+ labs( x= ", y="Deaths")

ggplot(data = Confirmed, aes(x = Country_Region , y= Confirmed, color = Country_Region)) + geom_point() + theme(legend.position="none") #+ labs( x= "Days", y="Confirmed")
```
### Exercise 6 March
```{r, eval=FALSE}
ggplot(data = US, aes(x = Province_State , y= Deaths, color = Province_State)) + geom_bar(stat="identity") + theme(legend.position="none") 
```

```{r, eval=FALSE}
country3<-report_09_13_2020%>%group_by(Country_Region) %>% summarise(Deaths= sum(Deaths))
```
```{r, eval=FALSE}
Deaths2<-country3%>%
arrange(desc(Deaths))%>%
slice(1:10)
View(Deaths)
```
```{r, eval=FALSE}
country4<-report_09_13_2020%>%group_by(Country_Region) %>% summarise(Confirmed= sum(Confirmed))
```
```{r, eval=FALSE}
Confirmed2<-country4%>%
arrange(desc(Confirmed))%>%
slice(1:10)
View(Confirmed)
```
```{r, eval=FALSE}
(US2<-report_09_13_2020)%>%
filter(Country_Region=="US") %>% 
group_by(Province_State) %>% 
summarise(Deaths= sum(Deaths)) %>% 
slice(1:10)
```
```{r, eval=FALSE}
(US3<-report_09_13_2020)%>%
filter(Country_Region=="US") %>% 
group_by(Province_State) %>% 
summarise(Confirmed= sum(Confirmed)) %>% 
slice(1:10)
```


### Exercise 5 September 
```{r, eval=FALSE}
ggplot(data = Deaths2, aes(x = Country_Region , y= Deaths, color = Country_Region)) + geom_point() + theme(legend.position="none") #+ labs( x= ", y="Deaths")

ggplot(data = Confirmed2, aes(x = Country_Region , y= Confirmed, color = Country_Region)) + geom_point() + theme(legend.position="none") #+ labs( x= "Days", y="Confirmed")
```

### Exercise 6 September
```{r, eval=FALSE}
ggplot(data = US2, aes(x = Province_State , y = Deaths , color = Province_State)) + geom_bar(stat="identity") + theme(legend.position = "none")
```
```{r, eval=FALSE}
ggplot(data = US3, aes(x = Province_State , y = Confirmed , color = Province_State)) + geom_bar(stat="identity") + theme(legend.position = "none")
```


