---
title: "Evo_Geno_Lab3A_Data_Wrangling"
author: "Danaiijah Vilsaint"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
summary(cars)
```

```{r}
library(tidyverse)
```

```{r, eval=FALSE}
surveys <- read.csv("data/portal_data_joined.csv")
```
```{r, eval=FALSE}
head(surveys)
```
```{r,eval=FALSE}
View(surveys)
```
```{r, eval=FALSE}
surveys <- read.csv("data/portal_data_joined.csv")
```

### Exercise 1
```{r, eval=FALSE}
surveys[200,]
```

### Exercise 2
```{r,eval=FALSE}
n_rows<- nrow(surveys)
surveys_last<- surveys[n_rows, ]
surveys_last
```

### Exercise 3
```{r,eval=FALSE}
surveys_middle<- surveys[n_rows / 2, ]
surveys_middle
```

### Exercise 4
```{r, eval=FALSE}
head_surveys <- surveys[-(7:n_rows), ]
head_surveys
```

### Ex 5
```{r, eval=FALSE}
levels(sex)[2:3] <- c("female", "male")
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(sex)
```

### Ex 6
```{r, eval=FALSE}
animal_data <- data.frame(
          animal=c("dog","cat","sea cucumber","sea urchin"),
          feel=c("furry", "furry","squishy", "spiny"),
          weight=c(45, 8, 1.1, 0.8) )
```
### EX 7
```{r, eval=FALSE}
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c("10", "30", "18", "15"),
       northern_hemisphere = c("TRUE", "TRUE", "FALSE", "FALSE"),
       has_kangaroo = c("FALSE", "FALSE", "FALSE", "TRUE")
      )

```



