---
title: "Evo_Geno_Lab4A"
author: "Danaiijah Vilsaint"
Date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```
```{r}
surveys_complete <- read_csv("data/surveys_complete.csv")
```

```{r, build}
### To build a ggplot, we will use the following basic template that can be used for different types of plots:
ggplot(data = surveys_complete, mapping = aes(x = weight, y = hindfoot_length))
```

```{r, new}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
  geom_point()
```

```{r, builditeravely}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point()
```

```{r, modify1}
ggplot(data = surveys_complete, aes(x = weight, y = hindfoot_length)) +
    geom_point(alpha = 0.1)
```

### Challenge
```{r, challenge1}
ggplot(data = surveys_complete, 
       mapping = aes(x = species_id, y = weight)) +
   geom_point(aes(color = plot_type))
```

```{r, boxplot}
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot()
```

```{r, addpoints}
ggplot(data = surveys_complete, mapping = aes(x = species_id, y = weight)) +
    geom_boxplot(alpha = 0) +
    geom_jitter(alpha = 0.3, color = "tomato")
```


